NKAYM/NKAYM/Models/Partner.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NKAYM.Models
{
    public class Partner
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string WebAdress { get; set; }
        public int Order { get; set; }

        [NotMapped]
        [Required]

        public IFormFile PartnerImageFile { get; set; }
    }
}

NKAYM/NKAYM/Areas/Admin/Controllers/PartnerController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using NKAYM.Constants;
using NKAYM.DAL;
using NKAYM.Models;
using NKAYM.Utils;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace NKAYM.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PartnerController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public PartnerController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            var partner = _context.Partners.OrderBy(p=>p.Order).ToList();
            return View(partner);
        }

        //create partner
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Partner partner)
        {
            if (!ModelState.IsValid) return View();

            if (!partner.PartnerImageFile.ContentType.Contains("image"))
            {
                ModelState.AddModelError("ImageFile", "Şəkil formatı uyğun gəlmir");
                return View();

            }

            if (partner.PartnerImageFile.Length > 1024 * 1024)
            {
                ModelState.AddModelError("ImageFile", "Şəkilin ölçüsü 1MB artıqdır");
                return View();
            }
           
            partner.Image = FileUtils.Create(FileConstants.PartnerImagePath, partner.PartnerImageFile);

            await _context.Partners.AddAsync(partner);
            await _context.SaveChangesAsync();


            return RedirectToAction(nameof(Index));
        }

        // delete partner
        public async Task<IActionResult> Delete(int id)
        {
            var delete = await _context.Partners.FindAsync(id);
            if (delete == null) return NotFound();

            return View(delete);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]

        public async Task<IActionResult> DeletePartner(int id)
        {
            var partnerDelete = await _context.Partners.FindAsync(id);
            if (partnerDelete == null) return NotFound();


            FileUtils.Delete(Path.Combine(FileConstants.PartnerImagePath, partnerDelete.Image));

            _context.Partners.Remove(partnerDelete);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        //update partner

        public async Task<IActionResult> Update(int id)
        {
            var news = await _context.Partners.FindAsync(id);

            if (news == null) return NotFound();

            return View(news);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, Partner partner)
        {
            var upPartner = await _context.Partners.FindAsync(id);

            if (upPartner == null) return NotFound();
            if (id != partner.Id) return BadRequest();
            if (!ModelState.IsValid) return View();
         
               
            
            FileUtils.Delete(Path.Combine(FileConstants.PartnerImagePath, upPartner.Image));

            upPartner.Image = FileUtils.Create(FileConstants.PartnerImagePath, partner.PartnerImageFile);

            upPartner.WebAdress = partner.WebAdress;
            upPartner.Order = partner.Order;
          


            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));



        }


        //detail partner
        public async Task<IActionResult> Detail(int id)
        {
            var partner = await _context.Partners.FindAsync(id);
            if (partner == null) return NotFound();
            return View(partner);
        }

    }
}

NKAYM/NKAYM/Areas/Admin/Views/Partner/Create.cshtml
@model Partner
@{
    ViewData["Title"] = "Create";
}
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <form class="forms-sample" method="post" asp-controller="Partner" asp-action="Create" enctype="multipart/form-data">
                           
                            <div class="form-group">
                                <label for="exampleInputUsername1">Şəkil*</label>
                                <input accept="image/*" asp-for="PartnerImageFile" class="form-control" placeholder="ImageFile">
                                <span asp-validation-for="PartnerImageFile" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputUsername1">Veb Ünvan*</label>
                                <input asp-for="WebAdress" class="form-control" placeholder="https://www.mail.ru/">
                                <span asp-validation-for="WebAdress" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputUsername1">SIRA*</label>
                                <textarea asp-for="Order" class="form-control" placeholder="SIRA"></textarea>
                                <span asp-validation-for="Order" class="text-danger"></span>
                            </div>
                           
                         

                            <button type="submit" class="btn btn-success me-2">Təsdiqlə</button>
                            <button class="btn btn-danger" asp-action="Index">Bağla</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

NKAYM/NKAYM/Areas/Admin/Views/Partner/Delete.cshtml
@model Partner
@{
    ViewData["Title"] = "Delete";
}



<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 grid-margin grid-margin-md-0 stretch-card">
                <div class="card">
                    <div class="card-body">


                        <h4 class="card-title"><img src="~/assets/images/partners/@Model.Image" style="width:300px; height:220px" /></h4>

                        <ul class="list-star" style="list-style:none;line-height:2;">
                           
                            <li><span style="color: red;font-weight:600">Veb Ünvan: </span>  @Model.WebAdress</li>
                            <li><span style="color: red;font-weight:600">SIRA:</span>  @Model.Order</li>
                          


                        </ul>

                        <form method="post" style="text-align:center">
                            <div class="buttons" style="display:inline;">
                                <button class="btn btn-danger " onclick="return confirm('Əminsiniz?');">Ləğv et</button>

                                <button class="btn btn-light ms-3" asp-action="Index">Bağla</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

NKAYM/NKAYM/Areas/Admin/Views/Partner/Detail.cshtml
@model Partner
@{
    ViewData["Title"] = "Detail";
}


<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 grid-margin grid-margin-md-0 stretch-card">
                <div class="card">
                    <div class="card-body">


                        <h4 class="card-title"><img src="~/assets/images/partners/@Model.Image" style="width:300px; height:220px" /></h4>

                        <ul class="list-star" style="list-style:none;line-height:2;">

                            <li><span style="color: red;font-weight:600">Veb Ünvan: </span>  @Model.WebAdress</li>
                            <li><span style="color: red;font-weight:600">SIRA:</span>  @Model.Order</li>



                        </ul>

                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

NKAYM/NKAYM/Areas/Admin/Views/Partner/Index.cshtml
@model List<Partner>
@{
    ViewData["Title"] = "Index";
}


<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12 ">
    <div class="mdc-card p-0 ">
        <div class="topic">

            <h6 class="card-title card-padding pb-0" style="color:white;font-size:40px;text-align:center; font-weight:600;">TƏRƏFDAŞLAR</h6>
            <a class="btn btn-success m-2" style="width:120px;" asp-controller="Partner" asp-action="Create">Yeni tərəfdaş</a>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered" style="border-color: black; text-align: center">
                <thead>
                    <tr style="background-color: #f7f7f7;text-align:center">

                        <th>ŞƏKİL</th>
                        <th>VEB ÜNVAN</th>
                        <th>SIRA</th>

                        <th>HƏRƏKƏTLƏR</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var partner in Model)
                    {
                    <tr>

                        <td> <img src="~/assets/images/partners/@partner.Image" alt="şəkil" style="width:200px;height:70px;border-radius:10px"></td>
                        <td> @partner.WebAdress </td>
                        <td> @partner.Order</td>
                        <td>
                            <a class="btn btn-warning mt-2" style="width:90px" asp-controller="Partner" asp-action="Update" asp-route-id="@partner.Id">Redaktə</a>

                            <a class="btn btn-primary mt-2" style="width:90px" asp-controller="Partner" asp-action="Detail" asp-route-id="@partner.Id">Məlumat</a>

                            <a class="btn btn-danger mt-2" style="width:90px" asp-controller="Partner" asp-action="Delete" asp-route-id="@partner.Id">Ləğv et</a>
                        </td>

                    </tr>
                    }


                </tbody>
            </table>
        </div>
    </div>
</div>

NKAYM/NKAYM/Areas/Admin/Views/Partner/Update.cshtml
@model Partner
@{
    ViewData["Title"] = "Update";
}

<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">

                        <form class="forms-sample" method="post" asp-controller="Partner" asp-action="Update" enctype="multipart/form-data">

                            <div class="form-group">
                                <label for="exampleInputUsername1">Şəkil*</label>
                                <input accept="image/*" asp-for="PartnerImageFile" class="form-control" placeholder="ImageFile">
                                <span asp-validation-for="PartnerImageFile" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputUsername1">Veb Ünvan*</label>
                                <input asp-for="WebAdress" class="form-control" placeholder="https://www.mail.ru/">
                                <span asp-validation-for="WebAdress" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputUsername1">SIRA*</label>
                                <textarea asp-for="Order" class="form-control" placeholder="SIRA"></textarea>
                                <span asp-validation-for="Order" class="text-danger"></span>
                            </div>



                            <button type="submit" class="btn btn-success me-2">Təsdiqlə</button>
                            <button class="btn btn-danger" asp-action="Index">Bağla</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>