NKAYM/NKAYM/Areas/Admin/Controllers/SubscribeController.cs
using Microsoft.AspNetCore.Mvc;
using NKAYM.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NKAYM.Areas.Admin.Controllers
{  [Area("Admin")]
    public class SubscribeController : Controller
    {
        private readonly AppDbContext _context;

        public SubscribeController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var subscribe = _context.Emails.ToList();
            return View(subscribe);
        }
        //delete subscribe
        public async Task<IActionResult> Delete(int id)
        {
            var message = await _context.Emails.FindAsync(id);
            if (message == null) return NotFound();

            _context.Emails.Remove(message);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

NKAYM/NKAYM/Areas/Admin/Views/Subscribe/Index.cshtml
@model List<Emails>
@{
    ViewData["Title"] = "Index";
}
<div class="mdc-layout-grid__cell stretch-card mdc-layout-grid__cell--span-12 ">
    <div class="mdc-card p-0 ">
        <div class="topic">

            <h6 class="card-title card-padding pb-0" style="color:white;font-size:40px;text-align:center; font-weight:600;">XƏBƏRDAR OLMAQ İSTƏYƏNLƏR</h6>
           
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered" style="border-color: black; text-align: center">
                <thead>
                    <tr style="background-color: #f7f7f7;text-align:center">

                        <th>E-POÇT ÜNVANI</th>

                        <th>HƏRƏKƏTLƏR</th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var email in Model)
                    {
                        <tr>

                            <td> @email.Email</td>

                            <td>

                                <a class="btn btn-primary" href="mailto:@email.Email">Xəbərdar et</a>
                                <a class="btn btn-danger" onclick="return confirm('Əminsiniz?')"; style="width:90px" asp-controller="Subscribe" asp-action="Delete" asp-route-id="@email.Id">Ləğv et</a>
                            </td>

                        </tr>
                    }


                </tbody>
            </table>
        </div>
    </div>
</div>